[package]
name = "web-desktop-environment-js-runtime"
version = "0.1.0"
authors = ["shmuelhizmi <shmuelhizmi1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.22.1"
url = "2.2.1"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
